-- MySQL Script generated by MySQL Workbench
-- Thu Aug 28 15:45:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sara2mini
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sara2mini
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sara2mini` DEFAULT CHARACTER SET utf8 ;
USE `sara2mini` ;

-- -----------------------------------------------------
-- Table `sara2mini`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Cursos` (
  `idCurso` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sigla` VARCHAR(10) NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Matrizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Matrizes` (
  `idMatriz` INT NULL AUTO_INCREMENT,
  `idCurso` INT NOT NULL,
  `anoInicio` DATE NOT NULL,
  PRIMARY KEY (`idMatriz`),
  INDEX `fk_Matrizes_1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Matrizes_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `sara2mini`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Disciplinas` (
  `idDisciplina` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargaHoraria` INT NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Turma` (
  `idTurma` INT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `semestre` SMALLINT(1) NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idTurma`),
  UNIQUE INDEX `matricula_UNIQUE` (`semestre` ASC) VISIBLE,
  INDEX `fk_Discentes_1_idx` (`idCurso` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Discentes_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `sara2mini`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Matriculas` (
  `idMatricula` INT NULL AUTO_INCREMENT,
  `idDiscente` INT NOT NULL,
  `idTurma` INT NOT NULL,
  `idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `fk_Matriculas_1_idx` (`idDisciplina` ASC) VISIBLE,
  INDEX `fk_Matriculas_2_idx` (`idDiscente` ASC) VISIBLE,
  CONSTRAINT `fk_Matriculas_1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `sara2mini`.`Disciplinas` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_2`
    FOREIGN KEY (`idDiscente`)
    REFERENCES `sara2mini`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Discentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Discentes` (
  `idDiscente` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `idCurso` INT NULL,
  PRIMARY KEY (`idDiscente`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Discentes_1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Discentes_1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `sara2mini`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`table1` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`RecursosAcademicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`RecursosAcademicos` (
  `idRecurso` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  PRIMARY KEY (`idRecurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Horarios` (
  `idHorarios` INT NOT NULL,
  `diaSemana` ENUM('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB') NOT NULL,
  `horaInicio` ENUM('7:30', '9:15', '11:00', '14:00', '15:45', '17:30', '19:00', '20:30') NOT NULL,
  `horaFim` ENUM('9:15', '11:00', '12:30', '13:45', '17:15', '19:00', '20:30', '22:00') NOT NULL,
  PRIMARY KEY (`idHorarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Alocacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Alocacoes` (
  `idAlocacoes` INT NOT NULL AUTO_INCREMENT,
  `idRecurso` INT NOT NULL,
  `idHorarios` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idAlocacoes`),
  INDEX `fk_Alocacoes_1_idx` (`idRecurso` ASC) VISIBLE,
  INDEX `fk_Alocacoes_2_idx` (`idHorarios` ASC) VISIBLE,
  CONSTRAINT `fk_Alocacoes_1`
    FOREIGN KEY (`idRecurso`)
    REFERENCES `sara2mini`.`RecursosAcademicos` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alocacoes_2`
    FOREIGN KEY (`idHorarios`)
    REFERENCES `sara2mini`.`Horarios` (`idHorarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Projetos` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Perfis` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `idPerfil` INT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuarios_1_idx` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `sara2mini`.`Perfis` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Modulos` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `idProjeto` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idModulo`),
  INDEX `fk_Modulos_1_idx` (`idProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Modulos_1`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `sara2mini`.`Projetos` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sara2mini`.`Artefatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sara2mini`.`Artefatos` (
  `idArtefato` INT NOT NULL AUTO_INCREMENT,
  `idModulo` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtefato`),
  INDEX `fk_Artefatos_1_idx` (`idModulo` ASC) VISIBLE,
  CONSTRAINT `fk_Artefatos_1`
    FOREIGN KEY (`idModulo`)
    REFERENCES `sara2mini`.`Modulos` (`idModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
